### ISSUE TITLE
日历组件，可以根据日期数组启用选择框吗？

### ISSUE THREAD

**Issue by cooper1x** [yued-fe/lulu#64]
就是比方说12月，只有12-18、12-20可以点击，其他任何日期都是不可选的禁用状态，目前有这个功能配置吗？

**Comment by zhangxinxu** [comment]
可以参考“标记特殊的日子，例如国庆节，劳动节等。”这个案例，在外部使用CSS进行样式控制。例如（IE10+）：
```css
.ui-date-item[data-date$="12-18"] {
    opacity: 0.35;
   -ms-pointer-events: none;
   pointer-events: none;
}
```
